/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.io.sofastack.cloud.trade;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import io.sofastack.cloud.trade.TradingApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class TradingApplication_SSTest extends TradingApplication_SSTest_scaffolding {
// allCoveredLines:[11, 13]

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      //caseID:db7d2066106c07516b302823db41be5f
      //CoveredLines: [11, 13]
      //Input_0_String[]: stringArray0
      
      TradingApplication tradingApplication0 = new TradingApplication();
      String[] stringArray0 = new String[0];
      
      //Call method: main
      // Undeclared exception!
      try { 
        TradingApplication.main(stringArray0);
      } catch(Throwable e) {
         verifyException("org.springframework.boot.autoconfigure.condition.OnClassCondition", e);
         assertEquals("java.lang.NullPointerException", e.getClass().getName());
      }
  }
}
