/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.io.sofastack.cloud.common.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import io.sofastack.cloud.common.model.TransferRequest;
import io.sofastack.cloud.common.utils.OrderUtils;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OrderUtils_SSTest extends OrderUtils_SSTest_scaffolding {
// allCoveredLines:[14, 17, 21, 25, 26, 30, 31, 32, 34, 35]

  @Test(timeout = 4000)
  public void test_getRandom_0()  throws Throwable  {
      //caseID:144f4daf8037a84525e5fd4a9ceb4dfb
      //CoveredLines: [14, 30, 34, 35]
      //Input_0_io.sofastack.cloud.common.model.TransferRequest: {}
      //Assert: assertEquals("002", method_result);
      
      OrderUtils orderUtils0 = new OrderUtils();
      //mock transferRequest0
      TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: getRandom
      Object object0 = PrivateAccess.callMethod((Class<OrderUtils>) OrderUtils.class, orderUtils0, "getRandom", (Object) transferRequest0, (Class<?>) TransferRequest.class);
      
      //Test Result Assert
      assertEquals("002", object0);
  }

  @Test(timeout = 4000)
  public void test_getSerialNo_1()  throws Throwable  {
      //caseID:edc52f60829e5d49dcc4b2fa1fad39c7
      //CoveredLines: [17, 25, 26, 30, 34, 35]
      //Input_0_TransferRequest: {getUserId=100}
      //Assert: assertEquals("20140214082121320001", method_result);
      
      //mock transferRequest0
      TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(100).when(transferRequest0).getUserId();
      
      //Call method: getSerialNo
      String string0 = OrderUtils.getSerialNo(transferRequest0);
      
      //Test Result Assert
      assertEquals("20140214082121320001", string0);
  }

  @Test(timeout = 4000)
  public void test_getSerialNo_2()  throws Throwable  {
      //caseID:9b885cadeeeef563e1b5d7d28cad4294
      //CoveredLines: [17, 25, 26, 30, 34, 35]
      //Input_0_TransferRequest: {}
      //Assert: assertEquals("20140214082121320001", method_result);
      
      //mock transferRequest0
      TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: getSerialNo
      String string0 = OrderUtils.getSerialNo(transferRequest0);
      
      //Test Result Assert
      assertEquals("20140214082121320001", string0);
  }

  @Test(timeout = 4000)
  public void test_getTradingNo_3()  throws Throwable  {
      //caseID:4ad602c62b8704fbd8ad0b8a099fd5ad
      //CoveredLines: [21, 25, 26, 30, 31, 32]
      //Input_0_TransferRequest: null
      //Assert: assertEquals("20140214082121320000", method_result);
      
      
      //Call method: getTradingNo
      String string0 = OrderUtils.getTradingNo((TransferRequest) null);
      
      //Test Result Assert
      assertEquals("20140214082121320000", string0);
  }

  @Test(timeout = 4000)
  public void test_getTradingNo_4()  throws Throwable  {
      //caseID:f8ccaa639ca4c63f7b979d9c524754a6
      //CoveredLines: [21, 25, 26, 30, 34, 35]
      //Input_0_TransferRequest: {}
      //Assert: assertEquals("20140214082121320001", method_result);
      
      //mock transferRequest0
      TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: getTradingNo
      String string0 = OrderUtils.getTradingNo(transferRequest0);
      
      //Test Result Assert
      assertEquals("20140214082121320001", string0);
  }
}
