/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.io.sofastack.cloud.web;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import io.sofastack.cloud.web.BizWebApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class)
@SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true)
public class BizWebApplication_SSTest extends BizWebApplication_SSTest_scaffolding {
    // allCoveredLines:[15]

    @Test(timeout = 4000)
    public void test_setCurrentTimeMillis_0() throws Throwable {
        //caseID:e27515a44efd60a90e85390242c85f16
        //CoveredLines: [15]

        BizWebApplication bizWebApplication0 = new BizWebApplication();
    }
}
