/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.io.sofastack.cloud.auth;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import io.sofastack.cloud.auth.SOFAAuthApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SOFAAuthApplication_SSTest extends SOFAAuthApplication_SSTest_scaffolding {
// allCoveredLines:[15]

  @Test(timeout = 4000)
  public void test_setCurrentTimeMillis_0()  throws Throwable  {
      //caseID:03d27c62cef0110e575a0d140ff99bd9
      //CoveredLines: [15]
      
      SOFAAuthApplication sOFAAuthApplication0 = new SOFAAuthApplication();
  }
}
