/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.io.sofastack.cloud.accounting;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import io.sofastack.cloud.accounting.AccountingApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class)
@SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true)
public class AccountingApplication_SSTest extends AccountingApplication_SSTest_scaffolding {
    // allCoveredLines:[11, 13]

    @Test(timeout = 4000)
    public void test_main_0() throws Throwable {
        //caseID:36a5304af347332b75bca2e8e0c3a8df
        //CoveredLines: [11, 13]
        //Input_0_String[]: stringArray0

        AccountingApplication accountingApplication0 = new AccountingApplication();
        String[] stringArray0 = new String[0];

        //Call method: main
        // Undeclared exception!
        try {
            AccountingApplication.main(stringArray0);
        } catch (Throwable e) {
            verifyException("org.springframework.boot.autoconfigure.condition.OnClassCondition", e);
            assertEquals("java.lang.NullPointerException", e.getClass().getName());
        }
    }
}
