/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.io.sofastack.cloud.mq.kafka.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import io.sofastack.cloud.mq.kafka.impl.MailServiceImpl;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import org.springframework.mail.javamail.JavaMailSender;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MailServiceImpl_SSTest extends MailServiceImpl_SSTest_scaffolding {
// allCoveredLines:[17, 19, 37, 38, 39, 40, 41, 43, 46, 47]

  @Test(timeout = 4000)
  public void test_sendTextMail_0()  throws Throwable  {
      //caseID:1ef4e6791891c123d4c6fe8c1dae2ee2
      //CoveredLines: [17, 19, 37, 38, 39, 40, 41, 43, 46, 47]
      //Input_0_String: ;C7q3
      //Input_1_String: ;C7q3
      //Input_2_String: ;C7q3
      
      MailServiceImpl mailServiceImpl0 = new MailServiceImpl();
      //mock javaMailSender0
      JavaMailSender javaMailSender0 = mock(JavaMailSender.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      PrivateAccess.setVariable((Class<?>) MailServiceImpl.class, mailServiceImpl0, "mailSender", (Object) javaMailSender0);
      
      //Call method: sendTextMail
      mailServiceImpl0.sendTextMail(";C7q3", ";C7q3", ";C7q3");
  }
}
