/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.io.sofastack.cloud.accounting.restrpc;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import io.sofastack.cloud.accounting.dao.AccountingMapper;
import io.sofastack.cloud.accounting.dao.SerialOrderMapper;
import io.sofastack.cloud.accounting.entity.AccountingEntity;
import io.sofastack.cloud.accounting.restrpc.AccountingServiceImpl;
import io.sofastack.cloud.common.model.BalanceDetails;
import io.sofastack.cloud.common.model.SerialOrder;
import io.sofastack.cloud.common.model.TransferRequest;
import io.sofastack.cloud.common.response.Result;
import java.math.BigDecimal;
import java.util.Map;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class)
@SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true)
public class AccountingServiceImpl_SSTest extends AccountingServiceImpl_SSTest_scaffolding {
    // allCoveredLines:[31, 43, 44, 45, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 70, 72, 73, 74, 75, 76, 77, 79, 80, 84, 85, 86, 87, 88, 89, 91, 92, 94, 95, 97, 98, 99, 101, 102, 103, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 117, 118, 123, 125, 126, 127, 128, 129, 131, 132, 134, 135, 136, 137, 138, 139, 144, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201]

    @Test(timeout = 4000)
    public void test_balanceDetail_00() throws Throwable {
        //caseID:e7bb68761dfe262ba0dac8497b08769a
        //CoveredLines: [31, 43, 44, 45, 46, 48, 49, 59, 60, 61, 62, 64]
        //Input_0_Map<String, Object>: {get=0}
        //Assert: assertFalse(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        Integer integer0 = new Integer(0);
        //mock map0
        Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(integer0).when(map0).get(any());

        //Call method: balanceDetail
        Result<BalanceDetails> result0 = accountingServiceImpl0.balanceDetail(map0);

        //Test Result Assert
        assertFalse(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_balanceDetail_01() throws Throwable {
        //caseID:9013ed2db59cb264c21357430b2ef4ed
        //CoveredLines: [31, 43, 44, 45, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 63, 64]
        //Input_0_Map<String, Object>: {get=0}
        //Assert: assertTrue(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        //mock accountingEntity0
        AccountingEntity accountingEntity0 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(accountingEntity0).when(accountingMapper0).queryById(anyInt());

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        Integer integer0 = new Integer(0);
        //mock map0
        Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(integer0).when(map0).get(any());

        //Call method: balanceDetail
        Result<BalanceDetails> result0 = accountingServiceImpl0.balanceDetail(map0);

        //Test Result Assert
        assertTrue(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_checkPayPassword_02() throws Throwable {
        //caseID:b4b13ff820bb3a5d5c3d6d365c69d857
        //CoveredLines: [31, 123, 125, 134, 135, 136, 137, 139]
        //Input_0_Map<String, Object>: {}
        //Assert: assertFalse(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        //mock map0
        Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

        //Call method: checkPayPassword
        Result<Boolean> result0 = accountingServiceImpl0.checkPayPassword(map0);

        //Test Result Assert
        assertFalse(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_checkPayPassword_03() throws Throwable {
        //caseID:2369f2c91ea114509e7601b38922a882
        //CoveredLines: [31, 123, 125, 126, 127, 128, 129, 138, 139]
        //Input_0_Map<String, Object>: {get=10 accountingServiceImpl0}
        //Assert: assertTrue(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(1).when(accountingMapper0).queryByIdAndPayPassword(anyInt(), anyString());

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        Integer integer0 = new Integer(10);
        //mock map0
        Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(integer0, accountingServiceImpl0).when(map0).get(any());

        //Call method: checkPayPassword
        Result<Boolean> result0 = accountingServiceImpl0.checkPayPassword(map0);

        //Test Result Assert
        assertTrue(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_checkPayPassword_04() throws Throwable {
        //caseID:2928c7e346b02c77ba6d7b1114db622e
        //CoveredLines: [31, 123, 125, 126, 127, 131, 132, 138, 139]
        //Input_0_Map<String, Object>: {get=0}
        //Assert: assertTrue(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        Integer integer0 = new Integer(0);
        //mock map0
        Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(integer0).when(map0).get(any());

        //Call method: checkPayPassword
        Result<Boolean> result0 = accountingServiceImpl0.checkPayPassword(map0);

        //Test Result Assert
        assertTrue(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_createAccount_05() throws Throwable {
        //caseID:52af22a8e344602f5c08d3d1ccb72299
        //CoveredLines: [31, 144, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 164, 165]
        //Input_0_Map<String, Object>: {get=accountingServiceImpl0 0}
        //Assert: assertTrue(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        Integer integer0 = new Integer(0);
        //mock map0
        Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(accountingServiceImpl0, integer0).when(map0).get(any());

        //Call method: createAccount
        Result<Boolean> result0 = accountingServiceImpl0.createAccount(map0);

        //Test Result Assert
        assertTrue(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_createAccount_06() throws Throwable {
        //caseID:312faabe6ea487e6ff4a515e59ccdeca
        //CoveredLines: [31, 144, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 160, 161, 162, 163, 165]
        //Input_0_Map<String, Object>: {}
        //Assert: assertFalse(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        //mock map0
        Map<String, Object> map0 = (Map<String, Object>) mock(Map.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

        //Call method: createAccount
        Result<Boolean> result0 = accountingServiceImpl0.createAccount(map0);

        //Test Result Assert
        assertFalse(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_transfer_07() throws Throwable {
        //caseID:979fae0c6ba9988f9df5a501854a459a
        //CoveredLines: [31, 70, 72, 73, 74, 75, 79, 80, 84, 85, 86, 87, 88, 89, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183]
        //Input_0_TransferRequest: {getTargetId=(-2), getAmountMoney=BigDecimal.TEN BigDecimal.TEN, getUserId=(-2) (-2) (-2)}
        //Assert: assertEquals("\u8D26\u6237\u4F59\u989D\u4E0D\u8DB3", method_result.getErrorMsg());
        //Assert: assertFalse(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        //mock accountingEntity0
        AccountingEntity accountingEntity0 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        BigDecimal bigDecimal0 = BigDecimal.TEN;
        //mock accountingEntity1
        AccountingEntity accountingEntity1 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0).when(accountingEntity1).getAvailableAssets();
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(accountingEntity1, accountingEntity0).when(accountingMapper0).queryById(anyInt());
        //mock serialOrderMapper0
        SerialOrderMapper serialOrderMapper0 = mock(SerialOrderMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn((-2)).when(serialOrderMapper0).save(
            any(io.sofastack.cloud.common.model.SerialOrder.class));

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "serialOrderMapper", (Object) serialOrderMapper0);

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        //mock transferRequest0
        TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0, bigDecimal0).when(transferRequest0).getAmountMoney();
        doReturn((-2)).when(transferRequest0).getTargetId();
        doReturn((-2), (-2), (-2)).when(transferRequest0).getUserId();

        //Call method: transfer
        Result<SerialOrder> result0 = accountingServiceImpl0.transfer(transferRequest0);

        //Test Result Assert
        assertEquals("\u8D26\u6237\u4F59\u989D\u4E0D\u8DB3", result0.getErrorMsg());

        //Test Result Assert
        assertFalse(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_transfer_08() throws Throwable {
        //caseID:576275443471334252ce5453edad0f89
        //CoveredLines: [31, 70, 72, 73, 74, 75, 76, 77, 84, 85, 91, 92, 94, 95, 97, 98, 99, 111, 112, 113, 114, 117, 118, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183]
        //Input_0_TransferRequest: {getTargetId=2198 9900, getRemark=\"org.springframework.messaging.tcp.reactor.ReactorNettyTcpClient$ReactorNettyHandler\", getAmountMoney=BigDecimal.ONE BigDecimal.ONE BigDecimal.ONE BigDecimal.TEN BigDecimal.TEN, getUserId=(-1) 9999 3860 (-1)}
        //Assert: assertFalse(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        BigDecimal bigDecimal0 = BigDecimal.TEN;
        //mock accountingEntity0
        AccountingEntity accountingEntity0 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0).when(accountingEntity0).getAvailableAssets();
        //mock accountingEntity1
        AccountingEntity accountingEntity1 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0, bigDecimal0).when(accountingEntity1).getAvailableAssets();
        doReturn(bigDecimal0).when(accountingEntity1).getFrozenAssets();
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(9999).when(accountingMapper0).frozonAssets(anyInt(),
            any(java.math.BigDecimal.class), any(java.math.BigDecimal.class));
        doReturn(accountingEntity1, accountingEntity0).when(accountingMapper0).queryById(anyInt());
        //mock serialOrderMapper0
        SerialOrderMapper serialOrderMapper0 = mock(SerialOrderMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(1).when(serialOrderMapper0).save(
            any(io.sofastack.cloud.common.model.SerialOrder.class));

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "serialOrderMapper", (Object) serialOrderMapper0);

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        BigDecimal bigDecimal1 = BigDecimal.ONE;
        //mock transferRequest0
        TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal1, bigDecimal1, bigDecimal1, bigDecimal0, bigDecimal0).when(
            transferRequest0).getAmountMoney();
        doReturn(
            "org.springframework.messaging.tcp.reactor.ReactorNettyTcpClient$ReactorNettyHandler")
            .when(transferRequest0).getRemark();
        doReturn(2198, 9900).when(transferRequest0).getTargetId();
        doReturn((-1), 9999, 3860, (-1)).when(transferRequest0).getUserId();

        //Call method: transfer
        Result<SerialOrder> result0 = accountingServiceImpl0.transfer(transferRequest0);

        //Test Result Assert
        assertFalse(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_transfer_09() throws Throwable {
        //caseID:0a0d51a6b45ce81159583907184aa0f1
        //CoveredLines: [31, 70, 72, 73, 74, 75, 76, 77, 84, 85, 91, 92, 94, 95, 97, 98, 99, 101, 102, 103, 105, 106, 107, 115, 117, 118, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201]
        //Input_0_TransferRequest: {getTargetId=0 0 0, getRemark=\"FORBID\", getAmountMoney=BigDecimal.TEN BigDecimal.ZERO BigDecimal.ZERO BigDecimal.TEN BigDecimal.ZERO BigDecimal.TEN BigDecimal.TEN BigDecimal.TEN BigDecimal.TEN, getUserId=0 0 0 0 0 0}
        //Assert: assertFalse(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        BigDecimal bigDecimal0 = BigDecimal.TEN;
        //mock accountingEntity0
        AccountingEntity accountingEntity0 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0).when(accountingEntity0).getAvailableAssets();
        doReturn(bigDecimal0).when(accountingEntity0).getTotalAssets();
        //mock accountingEntity1
        AccountingEntity accountingEntity1 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0, bigDecimal0).when(accountingEntity1).getAvailableAssets();
        doReturn(bigDecimal0).when(accountingEntity1).getFrozenAssets();
        doReturn(bigDecimal0).when(accountingEntity1).getTotalAssets();
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(0).when(accountingMapper0).deductAssets(anyInt(), any(java.math.BigDecimal.class),
            any(java.math.BigDecimal.class));
        doReturn(0).when(accountingMapper0).frozonAssets(anyInt(), any(java.math.BigDecimal.class),
            any(java.math.BigDecimal.class));
        doReturn(accountingEntity1, accountingEntity0).when(accountingMapper0).queryById(anyInt());
        doReturn(0).when(accountingMapper0).updateAvailableAssets(anyInt(),
            any(java.math.BigDecimal.class), any(java.math.BigDecimal.class));
        //mock serialOrderMapper0
        SerialOrderMapper serialOrderMapper0 = mock(SerialOrderMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(0, 0).when(serialOrderMapper0).save(
            any(io.sofastack.cloud.common.model.SerialOrder.class));

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "serialOrderMapper", (Object) serialOrderMapper0);

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        BigDecimal bigDecimal1 = BigDecimal.ZERO;
        //mock transferRequest0
        TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0, bigDecimal1, bigDecimal1, bigDecimal0, bigDecimal1, bigDecimal0,
            bigDecimal0, bigDecimal0, bigDecimal0).when(transferRequest0).getAmountMoney();
        doReturn("FORBID").when(transferRequest0).getRemark();
        doReturn(0, 0, 0).when(transferRequest0).getTargetId();
        doReturn(0, 0, 0, 0, 0, 0).when(transferRequest0).getUserId();

        //Call method: transfer
        Result<SerialOrder> result0 = accountingServiceImpl0.transfer(transferRequest0);

        //Test Result Assert
        assertFalse(result0.isSuccess());
    }

    @Test(timeout = 4000)
    public void test_transfer_10() throws Throwable {
        //caseID:b9b8a4798248bf189dac34d99080a1f6
        //CoveredLines: [31, 70, 72, 73, 74, 75, 76, 77, 84, 85, 91, 92, 94, 95, 97, 98, 99, 101, 102, 103, 105, 106, 107, 108, 109, 115, 117, 118, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201]
        //Input_0_TransferRequest: {getTargetId=6220 6220 6220, getRemark=\"FORBID\", getAmountMoney=BigDecimal.TEN BigDecimal.ZERO BigDecimal.ZERO BigDecimal.TEN BigDecimal.ZERO BigDecimal.TEN BigDecimal.TEN BigDecimal.TEN BigDecimal.TEN, getUserId=6220 6220 6220 6220 6220 6220}
        //Assert: assertTrue(method_result.isSuccess());

        AccountingServiceImpl accountingServiceImpl0 = new AccountingServiceImpl();
        BigDecimal bigDecimal0 = BigDecimal.TEN;
        //mock accountingEntity0
        AccountingEntity accountingEntity0 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0).when(accountingEntity0).getAvailableAssets();
        doReturn(bigDecimal0).when(accountingEntity0).getTotalAssets();
        //mock accountingEntity1
        AccountingEntity accountingEntity1 = mock(AccountingEntity.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0, bigDecimal0).when(accountingEntity1).getAvailableAssets();
        doReturn(bigDecimal0).when(accountingEntity1).getFrozenAssets();
        doReturn(bigDecimal0).when(accountingEntity1).getTotalAssets();
        //mock accountingMapper0
        AccountingMapper accountingMapper0 = mock(AccountingMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(6220).when(accountingMapper0).deductAssets(anyInt(),
            any(java.math.BigDecimal.class), any(java.math.BigDecimal.class));
        doReturn(6220).when(accountingMapper0).frozonAssets(anyInt(),
            any(java.math.BigDecimal.class), any(java.math.BigDecimal.class));
        doReturn(accountingEntity1, accountingEntity0).when(accountingMapper0).queryById(anyInt());
        doReturn(6220).when(accountingMapper0).updateAvailableAssets(anyInt(),
            any(java.math.BigDecimal.class), any(java.math.BigDecimal.class));
        //mock serialOrderMapper0
        SerialOrderMapper serialOrderMapper0 = mock(SerialOrderMapper.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(6220, 6220).when(serialOrderMapper0).save(
            any(io.sofastack.cloud.common.model.SerialOrder.class));

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "serialOrderMapper", (Object) serialOrderMapper0);

        PrivateAccess.setVariable((Class<?>) AccountingServiceImpl.class, accountingServiceImpl0,
            "accountingMapper", (Object) accountingMapper0);
        BigDecimal bigDecimal1 = BigDecimal.ZERO;
        //mock transferRequest0
        TransferRequest transferRequest0 = mock(TransferRequest.class, withSettings()
            .defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
        doReturn(bigDecimal0, bigDecimal1, bigDecimal1, bigDecimal0, bigDecimal1, bigDecimal0,
            bigDecimal0, bigDecimal0, bigDecimal0).when(transferRequest0).getAmountMoney();
        doReturn("FORBID").when(transferRequest0).getRemark();
        doReturn(6220, 6220, 6220).when(transferRequest0).getTargetId();
        doReturn(6220, 6220, 6220, 6220, 6220, 6220).when(transferRequest0).getUserId();

        //Call method: transfer
        Result<SerialOrder> result0 = accountingServiceImpl0.transfer(transferRequest0);

        //Test Result Assert
        assertTrue(result0.isSuccess());
    }
}
